/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourtCourtIdRouteImport } from './routes/court/$courtId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtCourtIdRoute = CourtCourtIdRouteImport.update({
  id: '/court/$courtId',
  path: '/court/$courtId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/court/$courtId': typeof CourtCourtIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/court/$courtId': typeof CourtCourtIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/court/$courtId': typeof CourtCourtIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/court/$courtId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/court/$courtId'
  id: '__root__' | '/' | '/court/$courtId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourtCourtIdRoute: typeof CourtCourtIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/court/$courtId': {
      id: '/court/$courtId'
      path: '/court/$courtId'
      fullPath: '/court/$courtId'
      preLoaderRoute: typeof CourtCourtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourtCourtIdRoute: CourtCourtIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
