export interface TennisCourt {
  id: string;
  name: string;
  location: string;
  address: string;
  surface: 'Hard' | 'Clay' | 'Grass' | 'Synthetic';
  indoor: boolean;
  lighting: boolean;
  hourlyRate: number;
  rating: number;
  amenities: string[];
  image: string;
  description: string;
  phone: string;
  website?: string;
}

export interface CourtReview {
  id: string;
  courtId: string;
  userName: string;
  rating: number;
  comment: string;
  date: string;
}

export const mockCourts: TennisCourt[] = [
  {
    id: "1",
    name: "Wimbledon Tennis Club",
    location: "London, UK",
    address: "Church Rd, Wimbledon, London SW19 5AE",
    surface: "Grass",
    indoor: false,
    lighting: true,
    hourlyRate: 85,
    rating: 4.9,
    amenities: ["Pro Shop", "Locker Rooms", "Restaurant", "Parking"],
    image: "https://photo-assets.wimbledon.com/images/pics/large/e_Ballot2026webhome.jpg",
    description: "Experience tennis on pristine grass courts at this prestigious club.",
    phone: "+44 20 8946 2244",
    website: "https://wimbledon.com",
  },
  {
    id: "2",
    name: "Central Park Tennis Center",
    location: "New York, NY",
    address: "Central Park West & 93rd St, New York, NY 10025",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 45,
    rating: 4.6,
    amenities: ["Equipment Rental", "Lessons", "Parking"],
    image: "https://images.ctfassets.net/cgcah00ul21b/3QFeUZYtPsVjRXlBlvhXXX/ca64868d04abfdc3b476ab563a356845/IMG_6584-1.jpg",
    description: "Public tennis courts in the heart of Manhattan with city skyline views.",
    phone: "+1 212-280-0205",
  },
  {
    id: "3",
    name: "Roland Garros Academy",
    location: "Paris, France",
    address: "2 Avenue Gordon Bennett, 75016 Paris",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 65,
    rating: 4.8,
    amenities: ["Pro Shop", "Coaching", "Restaurant", "Museum"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmDBF06Bj60B0ny610S5c37Fi4Q5d0mbfQPA&s",
    description: "Train on the same clay courts where champions are made.",
    phone: "+33 1 47 43 48 00",
  },
  {
    id: "4",
    name: "Melbourne Park Courts",
    location: "Melbourne, Australia",
    address: "Olympic Blvd, Melbourne VIC 3000",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 55,
    rating: 4.7,
    amenities: ["Air Conditioning", "Pro Shop", "Cafe", "Parking"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5xxjLfFMvgkDhbZHrmAfrtMmhtBgTHiOg2g&s",
    description: "State-of-the-art indoor courts with climate control.",
    phone: "+61 3 9286 1600",
  },
  {
    id: "5",
    name: "Sunset Beach Tennis Club",
    location: "Miami, FL",
    address: "1200 Ocean Drive, Miami Beach, FL 33139",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 40,
    rating: 4.5,
    amenities: ["Ocean View", "Bar", "Pool", "Parking"],
    image: "https://media.vrbo.com/lodging/79000000/78280000/78276600/78276579/b0cc1981.jpg",
    description: "Play tennis with stunning ocean views and Miami Beach atmosphere.",
    phone: "+1 305-673-7300",
  },
  {
    id: "6",
    name: "Alpine Tennis Resort",
    location: "Aspen, CO",
    address: "315 E Dean St, Aspen, CO 81611",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 75,
    rating: 4.8,
    amenities: ["Mountain Views", "Spa", "Restaurant", "Valet Parking"],
    image: "https://api.cloudly.space/resize/crop/1200/627/60/aHR0cHM6Ly9zdGF0aWMuYXBpZGFlLXRvdXJpc21lLmNvbS9maWxlc3RvcmUvb2JqZXRzLXRvdXJpc3RpcXVlcy9pbWFnZXMvMTAvMTQ4LzI0NDgyODI2LmpwZw==/image.jpg",
    description: "Luxury tennis experience surrounded by Rocky Mountain peaks.",
    phone: "+1 970-925-6200",
  },
  {
    id: "7",
    name: "Tokyo Tennis Garden",
    location: "Tokyo, Japan",
    address: "1-1-1 Shibuya, Shibuya City, Tokyo 150-0002",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 50,
    rating: 4.6,
    amenities: ["Modern Facilities", "Equipment Rental", "Cafe", "Subway Access"],
    image: "/placeholder.jpg",
    description: "Ultra-modern facility in the heart of Tokyo with cutting-edge synthetic courts.",
    phone: "+81 3-3463-1211",
  },
  {
    id: "8",
    name: "Desert Oasis Tennis Club",
    location: "Phoenix, AZ",
    address: "2901 N Central Ave, Phoenix, AZ 85012",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 35,
    rating: 4.4,
    amenities: ["Pool", "Shade Structures", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Desert tennis experience with stunning Sonoran landscape views.",
    phone: "+1 602-266-6896",
  },
  {
    id: "9",
    name: "Coastal Cliffs Tennis Center",
    location: "San Diego, CA",
    address: "2221 Morley Field Dr, San Diego, CA 92104",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 42,
    rating: 4.7,
    amenities: ["Ocean Breeze", "Pro Shop", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Clifftop courts with panoramic Pacific Ocean views.",
    phone: "+1 619-295-9278",
  },
  {
    id: "10",
    name: "Forest Hills Tennis Club",
    location: "Queens, NY",
    address: "1 Tennis Pl, Forest Hills, NY 11375",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 48,
    rating: 4.6,
    amenities: ["Historic Venue", "Pro Shop", "Restaurant", "Parking"],
    image: "/placeholder.webp",
    description: "Historic venue where tennis legends have played for decades.",
    phone: "+1 718-268-2300",
  },
  // Adding 40+ more courts to reach 50+
  {
    id: "11",
    name: "Riverside Tennis Academy",
    location: "Portland, OR",
    address: "1234 River Rd, Portland, OR 97201",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 38,
    rating: 4.3,
    amenities: ["River Views", "Coaching", "Cafe", "Bike Parking"],
    image: "/placeholder.jpg",
    description: "Scenic courts along the Willamette River with mountain backdrop.",
    phone: "+1 503-555-0123",
  },
  {
    id: "12",
    name: "Lakeside Tennis Resort",
    location: "Lake Tahoe, CA",
    address: "999 Lakeshore Blvd, South Lake Tahoe, CA 96150",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 60,
    rating: 4.8,
    amenities: ["Lake Views", "Resort Amenities", "Spa", "Valet"],
    image: "/placeholder.webp",
    description: "Breathtaking alpine lake views while playing at elevation.",
    phone: "+1 530-555-0456",
  },
  {
    id: "13",
    name: "Urban Tennis Hub",
    location: "Chicago, IL",
    address: "456 Michigan Ave, Chicago, IL 60611",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 44,
    rating: 4.5,
    amenities: ["Downtown Location", "Equipment Rental", "Lounge", "Parking"],
    image: "/placeholder.jpg",
    description: "Modern indoor facility in the heart of downtown Chicago.",
    phone: "+1 312-555-0789",
  },
  {
    id: "14",
    name: "Country Club Tennis Courts",
    location: "Atlanta, GA",
    address: "789 Peachtree St, Atlanta, GA 30309",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 52,
    rating: 4.7,
    amenities: ["Country Club", "Dining", "Pool", "Valet"],
    image: "/placeholder.webp",
    description: "Elegant clay courts at an exclusive country club setting.",
    phone: "+1 404-555-0321",
  },
  {
    id: "15",
    name: "Mountain View Tennis Center",
    location: "Denver, CO",
    address: "321 Alpine Way, Denver, CO 80202",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 41,
    rating: 4.4,
    amenities: ["Mountain Views", "Pro Shop", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "High-altitude tennis with stunning Rocky Mountain panoramas.",
    phone: "+1 303-555-0654",
  },
  {
    id: "16",
    name: "Bayfront Tennis Club",
    location: "San Francisco, CA",
    address: "567 Bay St, San Francisco, CA 94133",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 58,
    rating: 4.6,
    amenities: ["Bay Views", "Fog Lights", "Cafe", "Public Transit"],
    image: "/placeholder.webp",
    description: "Play tennis with iconic San Francisco Bay and Golden Gate views.",
    phone: "+1 415-555-0987",
  },
  {
    id: "17",
    name: "Prairie Tennis Complex",
    location: "Kansas City, MO",
    address: "890 Prairie Ave, Kansas City, MO 64111",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 32,
    rating: 4.2,
    amenities: ["Large Complex", "Tournaments", "Pro Shop", "Parking"],
    image: "/placeholder.jpg",
    description: "Expansive tennis complex serving the greater Kansas City area.",
    phone: "+1 816-555-0234",
  },
  {
    id: "18",
    name: "Tropical Tennis Paradise",
    location: "Honolulu, HI",
    address: "123 Aloha Dr, Honolulu, HI 96815",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 65,
    rating: 4.9,
    amenities: ["Ocean Views", "Tropical Setting", "Bar", "Beach Access"],
    image: "/placeholder.webp",
    description: "Paradise tennis courts surrounded by palm trees and ocean breezes.",
    phone: "+1 808-555-0567",
  },
  {
    id: "19",
    name: "Historic Tennis Grounds",
    location: "Boston, MA",
    address: "456 Commonwealth Ave, Boston, MA 02215",
    surface: "Grass",
    indoor: false,
    lighting: true,
    hourlyRate: 55,
    rating: 4.5,
    amenities: ["Historic Venue", "Traditional Style", "Clubhouse", "Parking"],
    image: "/placeholder.webp",
    description: "Traditional grass courts steeped in New England tennis history.",
    phone: "+1 617-555-0890",
  },
  {
    id: "20",
    name: "Skyline Tennis Center",
    location: "Seattle, WA",
    address: "789 Pine St, Seattle, WA 98101",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 46,
    rating: 4.4,
    amenities: ["City Views", "Modern Facility", "Cafe", "Light Rail"],
    image: "/placeholder.webp",
    description: "Modern courts with panoramic views of the Seattle skyline.",
    phone: "+1 206-555-0123",
  },
  // Continue with more courts...
  {
    id: "21",
    name: "Desert Springs Tennis Resort",
    location: "Las Vegas, NV",
    address: "321 Desert Springs Dr, Las Vegas, NV 89109",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 48,
    rating: 4.6,
    amenities: ["Resort Setting", "Pool", "Spa", "Valet"],
    image: "/placeholder.webp",
    description: "Luxury resort tennis with desert mountain backdrop.",
    phone: "+1 702-555-0456",
  },
  {
    id: "22",
    name: "Collegiate Tennis Center",
    location: "Austin, TX",
    address: "654 University Ave, Austin, TX 78712",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 28,
    rating: 4.3,
    amenities: ["Student Rates", "Coaching", "Equipment Rental", "Parking"],
    image: "/placeholder.webp",
    description: "University-affiliated courts open to the public with student discounts.",
    phone: "+1 512-555-0789",
  },
  {
    id: "23",
    name: "Waterfront Tennis Club",
    location: "Charleston, SC",
    address: "987 Harbor View Rd, Charleston, SC 29401",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 45,
    rating: 4.7,
    amenities: ["Harbor Views", "Southern Charm", "Restaurant", "Parking"],
    image: "/placeholder.webp",
    description: "Charming clay courts overlooking Charleston Harbor.",
    phone: "+1 843-555-0321",
  },
  {
    id: "24",
    name: "Metro Tennis Complex",
    location: "Minneapolis, MN",
    address: "147 Metro Blvd, Minneapolis, MN 55401",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 39,
    rating: 4.2,
    amenities: ["Climate Control", "Large Complex", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Year-round indoor tennis facility serving the Twin Cities.",
    phone: "+1 612-555-0654",
  },
  {
    id: "25",
    name: "Garden District Tennis",
    location: "New Orleans, LA",
    address: "258 Magazine St, New Orleans, LA 70130",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 42,
    rating: 4.5,
    amenities: ["Historic District", "Jazz Atmosphere", "Cafe", "Streetcar"],
    image: "/placeholder.webp",
    description: "Tennis courts in the heart of New Orleans' historic Garden District.",
    phone: "+1 504-555-0987",
  },
  // Adding more courts to reach 50+
  {
    id: "26",
    name: "Hillside Tennis Academy",
    location: "Nashville, TN",
    address: "369 Music Row, Nashville, TN 37203",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 36,
    rating: 4.4,
    amenities: ["Music City Views", "Coaching", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Tennis academy with views of Nashville's rolling hills.",
    phone: "+1 615-555-0234",
  },
  {
    id: "27",
    name: "Coastal Tennis Resort",
    location: "Virginia Beach, VA",
    address: "741 Atlantic Ave, Virginia Beach, VA 23451",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 44,
    rating: 4.6,
    amenities: ["Beach Access", "Ocean Views", "Resort Amenities", "Parking"],
    image: "/placeholder.webp",
    description: "Beachfront tennis courts with direct access to Virginia Beach.",
    phone: "+1 757-555-0567",
  },
  {
    id: "28",
    name: "Mountain Ridge Tennis",
    location: "Salt Lake City, UT",
    address: "852 Wasatch Dr, Salt Lake City, UT 84102",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 38,
    rating: 4.3,
    amenities: ["Mountain Views", "High Altitude", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "High-altitude tennis with spectacular Wasatch Mountain views.",
    phone: "+1 801-555-0890",
  },
  {
    id: "29",
    name: "River City Tennis Club",
    location: "Cincinnati, OH",
    address: "963 Riverfront Dr, Cincinnati, OH 45202",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 34,
    rating: 4.2,
    amenities: ["River Views", "Traditional Courts", "Clubhouse", "Parking"],
    image: "/placeholder.webp",
    description: "Classic clay courts overlooking the Ohio River valley.",
    phone: "+1 513-555-0123",
  },
  {
    id: "30",
    name: "Sunshine Tennis Center",
    location: "Tampa, FL",
    address: "159 Sunshine Blvd, Tampa, FL 33602",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 37,
    rating: 4.5,
    amenities: ["Year-Round Play", "Pro Shop", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Sunny Florida tennis courts perfect for year-round play.",
    phone: "+1 813-555-0456",
  },
  // Continue adding more courts...
  {
    id: "31",
    name: "Capitol Tennis Complex",
    location: "Washington, DC",
    address: "753 Constitution Ave, Washington, DC 20001",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 52,
    rating: 4.4,
    amenities: ["Capitol Views", "Government Rates", "Metro Access", "Security"],
    image: "/placeholder.webp",
    description: "Tennis facility with views of the nation's capital landmarks.",
    phone: "+1 202-555-0789",
  },
  {
    id: "32",
    name: "Vineyard Tennis Club",
    location: "Napa, CA",
    address: "486 Vineyard Rd, Napa, CA 94558",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 68,
    rating: 4.8,
    amenities: ["Wine Country", "Luxury Setting", "Restaurant", "Valet"],
    image: "/placeholder.webp",
    description: "Elegant tennis courts surrounded by world-famous vineyards.",
    phone: "+1 707-555-0321",
  },
  {
    id: "33",
    name: "Industrial Tennis Hub",
    location: "Detroit, MI",
    address: "357 Motor City Dr, Detroit, MI 48201",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 31,
    rating: 4.1,
    amenities: ["Urban Setting", "Affordable Rates", "Equipment Rental", "Parking"],
    image: "/placeholder.webp",
    description: "Modern tennis facility in Detroit's revitalized downtown area.",
    phone: "+1 313-555-0654",
  },
  {
    id: "34",
    name: "Ozark Tennis Resort",
    location: "Branson, MO",
    address: "741 Lake Rd, Branson, MO 65616",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 35,
    rating: 4.6,
    amenities: ["Lake Views", "Resort Setting", "Entertainment", "Parking"],
    image: "/placeholder.webp",
    description: "Tennis courts nestled in the scenic Ozark Mountains.",
    phone: "+1 417-555-0987",
  },
  {
    id: "35",
    name: "Tech Valley Tennis",
    location: "San Jose, CA",
    address: "852 Silicon Dr, San Jose, CA 95110",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 56,
    rating: 4.5,
    amenities: ["Tech Hub", "Modern Facility", "High-Speed WiFi", "EV Charging"],
    image: "/placeholder.webp",
    description: "State-of-the-art tennis facility in the heart of Silicon Valley.",
    phone: "+1 408-555-0234",
  },
  {
    id: "36",
    name: "Bluegrass Tennis Club",
    location: "Louisville, KY",
    address: "963 Derby Ln, Louisville, KY 40202",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 33,
    rating: 4.3,
    amenities: ["Southern Hospitality", "Traditional Courts", "Clubhouse", "Parking"],
    image: "/placeholder.webp",
    description: "Traditional clay courts in Kentucky's bluegrass region.",
    phone: "+1 502-555-0567",
  },
  {
    id: "37",
    name: "Cascade Tennis Center",
    location: "Spokane, WA",
    address: "147 Cascade Ave, Spokane, WA 99201",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 36,
    rating: 4.2,
    amenities: ["Mountain Views", "Indoor Comfort", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Indoor tennis facility with views of the Cascade Range.",
    phone: "+1 509-555-0890",
  },
  {
    id: "38",
    name: "Alamo Tennis Complex",
    location: "San Antonio, TX",
    address: "258 Alamo Plaza, San Antonio, TX 78205",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 32,
    rating: 4.4,
    amenities: ["Historic Location", "River Walk Access", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Tennis courts near the historic Alamo and River Walk.",
    phone: "+1 210-555-0123",
  },
  {
    id: "39",
    name: "Pine Forest Tennis Club",
    location: "Portland, ME",
    address: "369 Pine St, Portland, ME 04101",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 41,
    rating: 4.3,
    amenities: ["Forest Setting", "Seasonal Play", "Clubhouse", "Parking"],
    image: "/placeholder.webp",
    description: "Tennis courts surrounded by Maine's beautiful pine forests.",
    phone: "+1 207-555-0456",
  },
  {
    id: "40",
    name: "Gateway Tennis Arena",
    location: "St. Louis, MO",
    address: "741 Gateway Dr, St. Louis, MO 63101",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 38,
    rating: 4.2,
    amenities: ["Gateway Arch Views", "Modern Facility", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Modern tennis arena with views of the iconic Gateway Arch.",
    phone: "+1 314-555-0789",
  },
  // Adding final courts to exceed 50
  {
    id: "41",
    name: "Emerald City Tennis",
    location: "Eugene, OR",
    address: "852 Emerald Ave, Eugene, OR 97401",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 34,
    rating: 4.5,
    amenities: ["University Town", "Track & Field", "Coaching", "Parking"],
    image: "/placeholder.webp",
    description: "Tennis courts in Oregon's track and field capital.",
    phone: "+1 541-555-0321",
  },
  {
    id: "42",
    name: "Granite State Tennis",
    location: "Manchester, NH",
    address: "963 Granite Rd, Manchester, NH 03101",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 39,
    rating: 4.1,
    amenities: ["Four Seasons", "Indoor Comfort", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Year-round indoor tennis in New Hampshire's largest city.",
    phone: "+1 603-555-0654",
  },
  {
    id: "43",
    name: "Copper Canyon Tennis",
    location: "Tucson, AZ",
    address: "147 Canyon Dr, Tucson, AZ 85701",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 36,
    rating: 4.6,
    amenities: ["Desert Views", "Sunset Play", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Desert tennis courts with stunning Sonoran sunset views.",
    phone: "+1 520-555-0987",
  },
  {
    id: "44",
    name: "Prairie Wind Tennis",
    location: "Omaha, NE",
    address: "258 Prairie Ave, Omaha, NE 68102",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 29,
    rating: 4.0,
    amenities: ["Affordable Rates", "Community Center", "Equipment Rental", "Parking"],
    image: "/placeholder.webp",
    description: "Community tennis facility serving greater Omaha area.",
    phone: "+1 402-555-0234",
  },
  {
    id: "45",
    name: "Magnolia Tennis Gardens",
    location: "Jackson, MS",
    address: "369 Magnolia St, Jackson, MS 39201",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 31,
    rating: 4.4,
    amenities: ["Southern Charm", "Garden Setting", "Clubhouse", "Parking"],
    image: "/placeholder.webp",
    description: "Beautiful clay courts surrounded by magnolia trees.",
    phone: "+1 601-555-0567",
  },
  {
    id: "46",
    name: "Frontier Tennis Club",
    location: "Cheyenne, WY",
    address: "741 Frontier Dr, Cheyenne, WY 82001",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 28,
    rating: 4.2,
    amenities: ["Wide Open Spaces", "Mountain Views", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Tennis courts on the high plains with Rocky Mountain views.",
    phone: "+1 307-555-0890",
  },
  {
    id: "47",
    name: "Volcano Tennis Resort",
    location: "Hilo, HI",
    address: "852 Volcano Rd, Hilo, HI 96720",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 58,
    rating: 4.7,
    amenities: ["Volcano Views", "Tropical Setting", "Resort Amenities", "Parking"],
    image: "/placeholder.webp",
    description: "Unique tennis experience with active volcano backdrop.",
    phone: "+1 808-555-0123",
  },
  {
    id: "48",
    name: "First State Tennis",
    location: "Wilmington, DE",
    address: "963 First St, Wilmington, DE 19801",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 43,
    rating: 4.3,
    amenities: ["Historic State", "Modern Facility", "Pro Shop", "Train Access"],
    image: "/placeholder.webp",
    description: "Modern tennis facility in America's first state.",
    phone: "+1 302-555-0456",
  },
  {
    id: "49",
    name: "Last Frontier Tennis",
    location: "Anchorage, AK",
    address: "147 Arctic Ave, Anchorage, AK 99501",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 55,
    rating: 4.5,
    amenities: ["Arctic Views", "Heated Facility", "Equipment Rental", "Parking"],
    image: "/placeholder.webp",
    description: "Indoor tennis facility with stunning Alaskan mountain views.",
    phone: "+1 907-555-0789",
  },
  {
    id: "50",
    name: "Green Mountain Tennis",
    location: "Burlington, VT",
    address: "258 Mountain View Rd, Burlington, VT 05401",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 42,
    rating: 4.4,
    amenities: ["Mountain Views", "Seasonal Beauty", "Clubhouse", "Parking"],
    image: "/placeholder.webp",
    description: "Tennis courts with spectacular Green Mountain and Lake Champlain views.",
    phone: "+1 802-555-0321",
  },
  {
    id: "51",
    name: "Ocean State Tennis",
    location: "Providence, RI",
    address: "369 Ocean Dr, Providence, RI 02901",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 46,
    rating: 4.3,
    amenities: ["Coastal Access", "Historic City", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Tennis courts in the heart of New England's Ocean State.",
    phone: "+1 401-555-0654",
  },
  {
    id: "52",
    name: "Treasure State Tennis",
    location: "Billings, MT",
    address: "741 Treasure Ave, Billings, MT 59101",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 33,
    rating: 4.2,
    amenities: ["Big Sky Views", "Wide Open Courts", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Tennis under Montana's famous big sky with endless horizon views.",
    phone: "+1 406-555-0987",
  },
  {
    id: "53",
    name: "Harbor Lights Tennis",
    location: "Baltimore, MD",
    address: "200 Harbor Point, Baltimore, MD 21231",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 36,
    rating: 4.3,
    amenities: ["Waterfront", "Lessons", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Waterfront courts with views of the Inner Harbor.",
    phone: "+1 410-555-0101",
  },
  {
    id: "54",
    name: "Canyon View Tennis Park",
    location: "Scottsdale, AZ",
    address: "8800 E Canyon Rd, Scottsdale, AZ 85255",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 39,
    rating: 4.5,
    amenities: ["Shade Structures", "Pro Shop", "Ice Water Stations", "Parking"],
    image: "/placeholder.webp",
    description: "Desert-friendly hard courts with plenty of shade.",
    phone: "+1 480-555-0102",
  },
  {
    id: "55",
    name: "Seaside Racquet Club",
    location: "Santa Monica, CA",
    address: "2100 Ocean Ave, Santa Monica, CA 90405",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 57,
    rating: 4.6,
    amenities: ["Ocean Breeze", "Locker Rooms", "Cafe", "Parking"],
    image: "/placeholder.webp",
    description: "Steps from the beach with premium coastal conditions.",
    phone: "+1 310-555-0103",
  },
  {
    id: "56",
    name: "Red Rock Tennis Center",
    location: "Sedona, AZ",
    address: "55 Cathedral Rock Dr, Sedona, AZ 86336",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 48,
    rating: 4.7,
    amenities: ["Scenic Vistas", "Pro Shop", "Guided Clinics", "Parking"],
    image: "/placeholder.webp",
    description: "Play beneath Sedona’s iconic red rock formations.",
    phone: "+1 928-555-0104",
  },
  {
    id: "57",
    name: "Lighthouse Tennis Grounds",
    location: "Portland, ME",
    address: "9 Breakwater Rd, South Portland, ME 04106",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 33,
    rating: 4.2,
    amenities: ["Sea Air", "Lessons", "Equipment Rental", "Parking"],
    image: "/placeholder.webp",
    description: "Coastal community courts by the harbor lighthouse.",
    phone: "+1 207-555-0105",
  },
  {
    id: "58",
    name: "SkyCourt Indoor Tennis",
    location: "Newark, NJ",
    address: "1200 Raymond Blvd, Newark, NJ 07102",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 46,
    rating: 4.1,
    amenities: ["Climate Control", "Ball Machine", "Locker Rooms", "Parking"],
    image: "/placeholder.webp",
    description: "Year-round indoor synthetic courts near transit.",
    phone: "+1 973-555-0106",
  },
  {
    id: "59",
    name: "Golden Gate Tennis House",
    location: "San Francisco, CA",
    address: "501 Park Presidio, San Francisco, CA 94118",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 61,
    rating: 4.6,
    amenities: ["Park Setting", "Pro Shop", "Cafe", "Bike Parking"],
    image: "/placeholder.webp",
    description: "Public hard courts nestled by cypress groves.",
    phone: "+1 415-555-0107",
  },
  {
    id: "60",
    name: "Snowcap Tennis Pavilion",
    location: "Bozeman, MT",
    address: "77 Bridger Dr, Bozeman, MT 59715",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 40,
    rating: 4.4,
    amenities: ["Altitude Training", "Ball Machine", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Heated indoor facility for winter-proof play.",
    phone: "+1 406-555-0108",
  },
  {
    id: "61",
    name: "Blue Coast Tennis",
    location: "San Sebastián, Spain",
    address: "Paseo de Miraconcha 20, 20007 San Sebastián",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 52,
    rating: 4.7,
    amenities: ["Sea Views", "Tapas Bar", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Coastal clay with Basque culinary flair.",
    phone: "+34 943 555 109",
    website: "https://example-euskadi-tennis.es",
  },
  {
    id: "62",
    name: "Canal District Tennis",
    location: "Amsterdam, Netherlands",
    address: "Keizersgracht 110, 1015 Amsterdam",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 49,
    rating: 4.5,
    amenities: ["Tram Access", "Cafe", "Locker Rooms", "Bike Parking"],
    image: "/placeholder.webp",
    description: "Indoor courts tucked along historic canals.",
    phone: "+31 20 555 0110",
  },
  {
    id: "63",
    name: "Emerald Isle Courts",
    location: "Dublin, Ireland",
    address: "12 Phoenix Park Rd, Dublin 8",
    surface: "Grass",
    indoor: false,
    lighting: true,
    hourlyRate: 58,
    rating: 4.6,
    amenities: ["Tea Room", "Pro Shop", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Seasonal grass courts in a grand park setting.",
    phone: "+353 1 555 0111",
  },
  {
    id: "64",
    name: "Rivers of Paris Tennis",
    location: "Paris, France",
    address: "18 Quai de la Gare, 75013 Paris",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 54,
    rating: 4.5,
    amenities: ["Seine Views", "Cafe", "Locker Rooms", "Metro"],
    image: "/placeholder.webp",
    description: "Urban hard courts along the Seine.",
    phone: "+33 1 55 55 01 12",
  },
  {
    id: "65",
    name: "Andes Peak Tennis",
    location: "Cusco, Peru",
    address: "Av. de la Cultura 700, Cusco 08001",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 27,
    rating: 4.2,
    amenities: ["High Altitude", "Lessons", "Equipment Rental", "Parking"],
    image: "/placeholder.webp",
    description: "High-altitude play with Andean vistas.",
    phone: "+51 84 555 112",
  },
  {
    id: "66",
    name: "Harbour Bridge Tennis",
    location: "Sydney, Australia",
    address: "2A Dawes Point, Sydney NSW 2000",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 59,
    rating: 4.7,
    amenities: ["Harbour Views", "Cafe", "Locker Rooms", "Ferry Access"],
    image: "/placeholder.webp",
    description: "Iconic views under the Sydney skyline.",
    phone: "+61 2 5550 0113",
  },
  {
    id: "67",
    name: "Shinjuku Court Hub",
    location: "Tokyo, Japan",
    address: "3-2-1 Shinjuku, Shinjuku-ku, Tokyo 160-0022",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 53,
    rating: 4.6,
    amenities: ["Vending", "Ball Machine", "Locker Rooms", "JR Lines"],
    image: "/placeholder.webp",
    description: "Efficient, impeccably maintained indoor hub.",
    phone: "+81 3-5550-0114",
  },
  {
    id: "68",
    name: "Maple Leaf Tennis Centre",
    location: "Toronto, Canada",
    address: "100 Queens Quay W, Toronto, ON M5J 2N1",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 47,
    rating: 4.4,
    amenities: ["TTC Access", "Cafe", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Indoor hard courts on the waterfront.",
    phone: "+1 416-555-0115",
  },
  {
    id: "69",
    name: "Praça Verde Tennis",
    location: "São Paulo, Brazil",
    address: "Av. Paulista 1500, São Paulo - SP",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 29,
    rating: 4.3,
    amenities: ["City Center", "Samba Nights", "Locker Rooms", "Parking"],
    image: "/placeholder.webp",
    description: "Red clay oasis in a bustling metropolis.",
    phone: "+55 11 5550 0116",
  },
  {
    id: "70",
    name: "Cape Breeze Tennis",
    location: "Cape Town, South Africa",
    address: "1 Signal Hill Rd, Cape Town, 8001",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 31,
    rating: 4.5,
    amenities: ["Table Mountain Views", "Cafe", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Sea breezes and mountain views on every rally.",
    phone: "+27 21 555 0117",
  },
  {
    id: "71",
    name: "Riviera Tennis & Padel",
    location: "Nice, France",
    address: "25 Prom. des Anglais, 06000 Nice",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 62,
    rating: 4.7,
    amenities: ["Beachfront", "Padel Courts", "Restaurant", "Valet"],
    image: "/placeholder.webp",
    description: "Mediterranean clay with resort amenities.",
    phone: "+33 4 93 55 01 18",
  },
  {
    id: "72",
    name: "Nordic Dome Tennis",
    location: "Reykjavík, Iceland",
    address: "2 Laugardalur, 104 Reykjavík",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 50,
    rating: 4.6,
    amenities: ["Geothermal Showers", "Cafe", "Locker Rooms", "Parking"],
    image: "/placeholder.webp",
    description: "All-season dome with geothermal comforts.",
    phone: "+354 555 0119",
  },
  {
    id: "73",
    name: "Highland Green Courts",
    location: "Edinburgh, UK",
    address: "11 Arthur’s Seat Rd, Edinburgh EH8",
    surface: "Grass",
    indoor: false,
    lighting: true,
    hourlyRate: 49,
    rating: 4.4,
    amenities: ["Historic Park", "Pro Shop", "Tea Room", "Parking"],
    image: "/placeholder.webp",
    description: "Seasonal grass under castle vistas.",
    phone: "+44 131 555 0120",
  },
  {
    id: "74",
    name: "Riviera Maya Tennis Club",
    location: "Tulum, Mexico",
    address: "Carretera Tulum-Boca Paila Km 5, Tulum, Q.R.",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 34,
    rating: 4.5,
    amenities: ["Jungle Setting", "Fresh Juice Bar", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Jungle-framed hard courts by turquoise waters.",
    phone: "+52 984 555 0121",
  },
  {
    id: "75",
    name: "Kilimanjaro Courts",
    location: "Arusha, Tanzania",
    address: "5 Moshi Rd, Arusha",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 22,
    rating: 4.2,
    amenities: ["Mountain Views", "Locker Rooms", "Parking"],
    image: "/placeholder.webp",
    description: "Clay rallies with Africa’s rooftop in the distance.",
    phone: "+255 27 555 0122",
  },
  {
    id: "76",
    name: "Bosphorus Tennis Park",
    location: "Istanbul, Türkiye",
    address: "Dolmabahçe Cd. 10, Beşiktaş/İstanbul",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 38,
    rating: 4.4,
    amenities: ["Bridge Views", "Tea Garden", "Locker Rooms", "Tram"],
    image: "/placeholder.webp",
    description: "Cross-continental rallies by the Bosphorus.",
    phone: "+90 212 555 0123",
  },
  {
    id: "77",
    name: "Alpine Meadow Tennis",
    location: "Zermatt, Switzerland",
    address: "2 Bahnhofstrasse, 3920 Zermatt",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 64,
    rating: 4.8,
    amenities: ["Matterhorn Views", "Pro Shop", "Cafe", "Ski Lift Access"],
    image: "/placeholder.webp",
    description: "Glacier air and alpine serenity meet center court.",
    phone: "+41 27 555 0124",
  },
  {
    id: "78",
    name: "Sahara Edge Tennis",
    location: "Marrakesh, Morocco",
    address: "Avenue Mohammed VI, Marrakesh 40000",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 27,
    rating: 4.3,
    amenities: ["Riads Nearby", "Mint Tea Lounge", "Locker Rooms", "Parking"],
    image: "/placeholder.webp",
    description: "Rust-red clay by palm groves and riads.",
    phone: "+212 524 555 0125",
  },
  {
    id: "79",
    name: "Nordstadt Tennis Forum",
    location: "Berlin, Germany",
    address: "Bernauer Str. 100, 13355 Berlin",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 45,
    rating: 4.5,
    amenities: ["U-Bahn", "Cafe", "Ball Machine", "Locker Rooms"],
    image: "/placeholder.webp",
    description: "Urban indoor forum with efficient booking.",
    phone: "+49 30 555 0126",
  },
  {
    id: "80",
    name: "Opera House Tennis",
    location: "Vienna, Austria",
    address: "Karlsplatz 2, 1010 Wien",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 48,
    rating: 4.4,
    amenities: ["Historic Center", "Cafe", "Lessons", "Metro Access"],
    image: "/placeholder.webp",
    description: "Courts in Vienna’s cultured heart.",
    phone: "+43 1 555 0127",
  },
  {
    id: "81",
    name: "Cathedral Tennis Gardens",
    location: "Seville, Spain",
    address: "C. Alemanes 5, 41004 Sevilla",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 31,
    rating: 4.5,
    amenities: ["Orange Trees", "Tapas Bar", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Andalusian clay shaded by citrus trees.",
    phone: "+34 95 455 50 128",
  },
  {
    id: "82",
    name: "Harbour City Tennis",
    location: "Hong Kong",
    address: "3 Canton Rd, Tsim Sha Tsui",
    surface: "Hard",
    indoor: true,
    lighting: true,
    hourlyRate: 66,
    rating: 4.6,
    amenities: ["MTR Access", "Locker Rooms", "Cafe", "Pro Shop"],
    image: "/placeholder.webp",
    description: "Skyscraper views from climate-controlled courts.",
    phone: "+852 5550 0129",
  },
  {
    id: "83",
    name: "Outback Tennis Retreat",
    location: "Alice Springs, Australia",
    address: "1 Todd Mall, Alice Springs NT 0870",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 24,
    rating: 4.1,
    amenities: ["Desert Air", "Shade", "Equipment Rental", "Parking"],
    image: "/placeholder.webp",
    description: "Quiet, starlit night sessions under the Outback sky.",
    phone: "+61 8 5550 0130",
  },
  {
    id: "84",
    name: "Baltic Breeze Tennis",
    location: "Riga, Latvia",
    address: "Krišjāņa Barona iela 50, Rīga",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 28,
    rating: 4.2,
    amenities: ["Sauna", "Cafe", "Locker Rooms", "Tram"],
    image: "/placeholder.webp",
    description: "Cozy dome courts for long Baltic winters.",
    phone: "+371 5550 0131",
  },
  {
    id: "85",
    name: "Danube Riverside Courts",
    location: "Budapest, Hungary",
    address: "Bem rakpart 20, 1027 Budapest",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 26,
    rating: 4.3,
    amenities: ["Thermal Baths Nearby", "Cafe", "Locker Rooms", "Tram"],
    image: "/placeholder.webp",
    description: "Clay with river breezes and spa culture.",
    phone: "+36 1 555 0132",
  },
  {
    id: "86",
    name: "Polar Night Tennis",
    location: "Tromsø, Norway",
    address: "Storgata 81, 9008 Tromsø",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 51,
    rating: 4.5,
    amenities: ["Aurora Sightings", "Heated Dome", "Cafe", "Parking"],
    image: "/placeholder.webp",
    description: "Chase the Northern Lights after your match.",
    phone: "+47 77 55 0133",
  },
  {
    id: "87",
    name: "Celtic Hills Tennis",
    location: "Galway, Ireland",
    address: "12 Eyre Square, Galway",
    surface: "Grass",
    indoor: false,
    lighting: true,
    hourlyRate: 37,
    rating: 4.2,
    amenities: ["Tea Room", "Lessons", "Locker Rooms", "Parking"],
    image: "/placeholder.webp",
    description: "Soft grass and brisk Atlantic breezes.",
    phone: "+353 91 555 0134",
  },
  {
    id: "88",
    name: "Mekong Riverside Tennis",
    location: "Ho Chi Minh City, Vietnam",
    address: "15 Ton Duc Thang, District 1",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 18,
    rating: 4.1,
    amenities: ["Riverside", "Cafe", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Busy river scenes frame your serves.",
    phone: "+84 28 5550 0135",
  },
  {
    id: "89",
    name: "Saffron Court Complex",
    location: "Jaipur, India",
    address: "Amer Rd, Jaipur, Rajasthan 302002",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 14,
    rating: 4.0,
    amenities: ["Heritage Views", "Tea Stall", "Locker Rooms", "Parking"],
    image: "/placeholder.webp",
    description: "Royal-hued sunsets over terracotta courts.",
    phone: "+91 141 555 0136",
  },
  {
    id: "90",
    name: "Volta Bay Tennis",
    location: "Accra, Ghana",
    address: "6 Independence Ave, Accra",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 16,
    rating: 4.1,
    amenities: ["Sea Breeze", "Lessons", "Locker Rooms", "Parking"],
    image: "/placeholder.webp",
    description: "Coastal community hub for rising players.",
    phone: "+233 30 255 0137",
  },
  {
    id: "91",
    name: "Baltoro Heights Tennis",
    location: "Skardu, Pakistan",
    address: "1 K2 View Rd, Skardu",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 12,
    rating: 4.2,
    amenities: ["High Peaks View", "Equipment Rental", "Parking"],
    image: "/placeholder.webp",
    description: "Thin air, towering Karakoram vistas.",
    phone: "+92 581 5550138",
  },
  {
    id: "92",
    name: "Coral Coast Tennis",
    location: "Suva, Fiji",
    address: "Queen’s Rd, Suva",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 20,
    rating: 4.3,
    amenities: ["Tropical Setting", "Fresh Coconut Bar", "Parking"],
    image: "/placeholder.webp",
    description: "Island vibes and salt-tinged air.",
    phone: "+679 555 0139",
  },
  {
    id: "93",
    name: "Sicilian Terrace Tennis",
    location: "Taormina, Italy",
    address: "Via Teatro Greco 1, 98039 Taormina ME",
    surface: "Clay",
    indoor: false,
    lighting: true,
    hourlyRate: 44,
    rating: 4.6,
    amenities: ["Sea Terraces", "Espresso Bar", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Cliffside clay with Ionian panoramas.",
    phone: "+39 0942 555 0140",
  },
  {
    id: "94",
    name: "Sakura Riverside Courts",
    location: "Kyoto, Japan",
    address: "3 Kamo River Rd, Kyoto 600-8010",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 41,
    rating: 4.6,
    amenities: ["Cherry Blossoms", "Tea House", "Locker Rooms", "Bus"],
    image: "/placeholder.webp",
    description: "Spring petals drifting across baseline rallies.",
    phone: "+81 75-555-0141",
  },
  {
    id: "95",
    name: "Emerald Forest Tennis",
    location: "Vancouver, Canada",
    address: "333 Stanley Park Dr, Vancouver, BC",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 43,
    rating: 4.5,
    amenities: ["Evergreen Shade", "Seawall Access", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Forest-lined courts by the seawall.",
    phone: "+1 604-555-0142",
  },
  {
    id: "96",
    name: "Ipanema Tennis Terrace",
    location: "Rio de Janeiro, Brazil",
    address: "Av. Vieira Souto 300, Ipanema",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 37,
    rating: 4.4,
    amenities: ["Beachfront", "Acai Bar", "Locker Rooms", "Parking"],
    image: "/placeholder.webp",
    description: "Beach rhythm meets clean hard-court bounce.",
    phone: "+55 21 5550 0143",
  },
  {
    id: "97",
    name: "Saharan Star Courts",
    location: "Tozeur, Tunisia",
    address: "Palmeraie de Tozeur, 2200",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 23,
    rating: 4.1,
    amenities: ["Oasis Dome", "Cafe", "Locker Rooms", "Parking"],
    image: "/placeholder.webp",
    description: "Oasis-cooled dome in date-palm country.",
    phone: "+216 76 555 0144",
  },
  {
    id: "98",
    name: "Bayside Community Tennis",
    location: "Auckland, New Zealand",
    address: "1 Tamaki Dr, Auckland 1071",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 35,
    rating: 4.4,
    amenities: ["Harbor Views", "Lessons", "Pro Shop", "Parking"],
    image: "/placeholder.webp",
    description: "Harbor wind adds spin to your serves.",
    phone: "+64 9 555 0145",
  },
  {
    id: "99",
    name: "Siberian Light Tennis Dome",
    location: "Novosibirsk, Russia",
    address: "50 Krasny Prospekt, Novosibirsk",
    surface: "Synthetic",
    indoor: true,
    lighting: true,
    hourlyRate: 21,
    rating: 4.0,
    amenities: ["Heated Dome", "Sauna", "Locker Rooms", "Metro"],
    image: "/placeholder.webp",
    description: "Warm rallies despite sub-zero winters.",
    phone: "+7 383 555-0146",
  },
  {
    id: "100",
    name: "Petra Sunset Courts",
    location: "Wadi Musa, Jordan",
    address: "Tourist St 10, Wadi Musa",
    surface: "Hard",
    indoor: false,
    lighting: true,
    hourlyRate: 25,
    rating: 4.3,
    amenities: ["Rose-Red Cliffs", "Tea Lounge", "Lessons", "Parking"],
    image: "/placeholder.webp",
    description: "Ancient sandstone glow at golden hour.",
    phone: "+962 3 555 0147",
  }
];

export const mockReviews: CourtReview[] = [
  {
    id: "1",
    courtId: "1",
    userName: "Sarah Johnson",
    rating: 5,
    comment:
      "Absolutely incredible experience! The grass courts are pristine and the atmosphere is unmatched. Worth every penny.",
    date: "2024-01-15",
  },
  {
    id: "2",
    courtId: "1",
    userName: "Mike Chen",
    rating: 5,
    comment: "Playing on these historic courts was a dream come true. Professional staff and immaculate facilities.",
    date: "2024-01-10",
  },
  {
    id: "3",
    courtId: "2",
    userName: "Emily Rodriguez",
    rating: 4,
    comment: "Great location in Central Park. Courts are well-maintained and the city views are amazing.",
    date: "2024-01-12",
  },
  {
    id: "4",
    courtId: "2",
    userName: "David Kim",
    rating: 5,
    comment: "Perfect for a morning game before work. Easy booking system and friendly staff.",
    date: "2024-01-08",
  },
  {
    id: "5",
    courtId: "3",
    userName: "Marie Dubois",
    rating: 5,
    comment: "Les courts en terre battue sont magnifiques! Une expérience authentique à Roland Garros.",
    date: "2024-01-14",
  },
  {
    id: "6",
    courtId: "3",
    userName: "Hiro Tanaka",
    rating: 4,
    comment: "Clay courts are top notch. Felt like the French Open.",
    date: "2025-04-10",
  },
  {
    id: "7",
    courtId: "4",
    userName: "Sophie Martin",
    rating: 5,
    comment: "Indoor hard courts are pristine, and the atmosphere is electric.",
    date: "2025-05-02",
  },
  {
    id: "8",
    courtId: "5",
    userName: "Liam O'Connor",
    rating: 3,
    comment: "Courts were fine, but the cafe service was a bit slow.",
    date: "2025-05-15",
  },
  {
    id: "9",
    courtId: "4",
    userName: "Alice Johnson",
    rating: 5,
    comment: "The grass here feels incredible to play on. Worth every penny!",
    date: "2025-01-12",
  },
  {
    id: "10",
    courtId: "6",
    userName: "David Lee",
    rating: 4,
    comment: "Beautiful club, though the membership fees are steep.",
    date: "2025-02-03",
  },
  {
    id: "11",
    courtId: "7",
    userName: "Maria Gonzalez",
    rating: 5,
    comment: "Perfect location and affordable prices. Love playing after work.",
    date: "2025-03-21",
  },
];